// React Study/day19/src/App.tsx
/*
 * @Author: your name
 * @Date: 2020-05-27 21:12:28
 * @LastEditTime: 2020-05-29 08:46:51
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \My-JavaScript-Study\React Study\day19\src\App.js
 */

import React, { Fragment } from "react";
import "./App.css";
import Header from "./containers/header";
function App() {
  return (
    <Fragment>
      <Header />
    </Fragment>
  );
}

export default App;

// Vue Study/my-vue/App.vue
<!--
 * @Author: your name
 * @Date: 2020-05-03 23:07:05
 * @LastEditTime: 2020-05-04 10:16:36
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \My-JavaScript-Study\Vue Study\my-vue\App.vue
 -->
 <template>
   <div>
      {{message}}
   </div>
 </template>

 <script>
 export default {
   name:"App",
   data(){
     return{
        message:"hello pangchao"
     }
   }
 }
 </script>

 <style scoped>
   div{
    color:orange;
    font-size:18px;
    font-weight: bold;
   }
 </style>
